const TournamentActionTypes = {
  GET_ALL_TOURNAMENTS: "GET_ALL_TOURNAMENTS",
  TOURNAMENT_ERROR: "TOURNAMENT_ERROR",
  TOURNAMENTS_ERROR: "TOURNAMENTS_ERROR",
  GET_FAVORITES: "GET_FAVORITES",
  GET_FAVORITES_ERROR: "GET_FAVORITES_ERROR",
  ADD_FAVORITE: "ADD_FAVORITE",
  ADD_FAVORITE_ERROR: "ADD_FAVORITE_ERROR",
  DELETE_FAVORITE: "DELETE_FAVORITE"
};

export default TournamentActionTypes;
